/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.mpicbg.sqeazyio;

import org.junit.Test;
import static org.junit.Assert.*;

import de.mpicbg.sqeazyio.SqeazyFormat;

public class SQYFormatTest {
    // @Test public void testSomeLibraryMethod() {
    //     Library classUnderTest = new Library();
    //     assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    //  }

    @Test public void testFormatNameMethod() {

        SqeazyFormat f = new SqeazyFormat();

        String obs = f.getFormatName();
        final String exp = "sqeazy";
        assertEquals(exp,obs);
    }



}
