/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import de.mpicbg.sqeazy.SqeazyFormat.Metadata;

public class SQYMetadataTest {

    @Test public void testType() {

        Metadata md = // new SqeazyFormat().
            new Metadata();


        md.setType("j");
        assertEquals(md.getType(),"j");
    }

    @Test public void testPipeline() {

        Metadata md = // new SqeazyFormat().
            new Metadata();


        md.setPipeline("bitswap->lz4");
        assertEquals(md.getPipeline(),"bitswap->lz4");
    }

    @Test public void testPopulateMD() {

        final String header = "\"pipename\": \"bitswap1(num_bits_per_plane=1)->lz4(accel=1,blocksize_kb=256,framestep_kb=256,n_chunks_of_input=0)\",\n"
+ "\"raw\": {                 \n"
+ "    \"type\": \"h\",         \n"
+ "    \"rank\": \"3\",         \n"
+ "    \"shape\": {           \n"
+ "        \"dim\": \"57\",     \n"
+ "        \"dim\": \"256\",    \n"
+ "        \"dim\": \"256\"     \n"
+ "    }                    \n"
+ "},                       \n"
+ "\"encoded\": {             \n"
+ "    \"bytes\": \"1072574\"   \n"
+ "},                       \n"
+ "\"sqy\": {                 \n"
+ "    \"version\": \"0.5.2\",  \n"
+ "    \"headref\": \"35dc9a6\" \n"
+ "}                        \n";

        Metadata md = new Metadata();
        md.setData(header.getBytes());
        //TODO: doesn't work due to get(0) md.populateImageMetadata();
        //assertEquals(md.getType(),"h");
        assertEquals(md.getData()[1],'p');
    }

}
