/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.mpicbg.sqeazyio;

import io.scif.img.IO;
import io.scif.config.SCIFIOConfig;
import io.scif.io.RandomAccessInputStream;
import io.scif.ImageMetadata;
import io.scif.FormatException;

import java.net.URL;
import java.io.IOException;
import java.nio.file.*;

import org.junit.Test;
import org.junit.After;
import org.junit.Before;
import org.junit.AfterClass;
import org.junit.BeforeClass;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.*;

import org.scijava.Context;
import net.imagej.axis.Axes;

import org.bridj.Pointer;
import org.bridj.CLong;
import static org.bridj.Pointer.*;
import sqeazy.bindings.SqeazyLibrary;

import de.mpicbg.sqeazyio.SqeazyFormat.Parser;
//import de.mpicbg.sqeazyio.SqeazyFormat.Reader;
import de.mpicbg.sqeazyio.SqeazyFormat.Metadata;
import de.mpicbg.sqeazyio.SqeazyFormat;

public class SQYParserTest {

    private static final Context context = new Context();
	private static final SqeazyFormat format = new SqeazyFormat();
	private static SqeazyFormat.Reader reader;
	private static SqeazyFormat.Parser parser;
	private static final SqeazyFormat.Checker checker = new SqeazyFormat.Checker();

    @BeforeClass
	public static void oneTimeSetup() throws Exception {
		format.setContext(context);
		reader = (SqeazyFormat.Reader) format.createReader();
		parser = (SqeazyFormat.Parser) format.createParser();
	}

	@Before
	public void setUp() throws Exception {}

	@AfterClass
	public static void oneTimeTearDown() {
		context.dispose();
	}

// /home/steinbac/software/scifio/src/test/java/io/scif/formats/KontronFormatTest.java
    @Test public void testCorrectWidthHeight() throws IOException, FormatException {

        final URL tiny = getClass().getResource("flybrain.sqy");
        assertNotEquals(tiny,null);

        final String fpath = tiny.getPath();
        final Path fnio = Paths.get(fpath);
        assertThat(fpath, containsString("de/mpicbg/sqeazyio/flybrain.sqy"));
        assertEquals(Files.isRegularFile(fnio), true);

        final SqeazyFormat.Metadata sqyMeta = new SqeazyFormat.Metadata();
        final RandomAccessInputStream stream = new RandomAccessInputStream(context, fpath);
        final int blockLen = 4 << 10;
        final String data = stream.readString(blockLen);
        assertThat(data, containsString("pipename"));
        assertThat(data, containsString("rank"));
        final SCIFIOConfig config = new SCIFIOConfig();

        assertNotEquals(stream, null);
		assertNotEquals(reader, null);

        reader.setSource(stream);
        parser.typedParse(stream, sqyMeta, config);

// VERIFY
        assertEquals(256, sqyMeta.getSizeX());
		assertEquals(256, sqyMeta.getSizeY());
        assertEquals(57, sqyMeta.getSizeZ());

        final ImageMetadata iMeta = sqyMeta.get(0);

        assertEquals(57, iMeta.getAxisLength(Axes.Z));

    }



}
