/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import de.mpicbg.sqeazy.SqeazyFormat.Checker;

public class SQYCheckerTest {

    @Test public void testType() {

        assertEquals("f","j");
    }


}
