/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import io.scif.img.IO;
import io.scif.config.SCIFIOConfig;
import io.scif.formats.FakeFormat;
import io.scif.io.RandomAccessInputStream;

import java.net.URL;
import java.io.IOException;

import org.junit.Test;
import org.junit.After;
import org.junit.Before;
import static org.junit.Assert.*;
import org.scijava.Context;

import de.mpicbg.sqeazy.SqeazyFormat.Checker;

public class SQYCheckerTest {

    private Context context;
    private Checker c;

    @Before
    public void setUp() {
        context = new Context();
        //final SCIFIO scifio = new SCIFIO();
        // final Format f = scifio.format().getFormat(id);
        // c = f.createChecker();
        c = new Checker();
        c.setContext(context);
    }

    @After
	public void tearDown() {
		context = null;
		c = null;
	}

    @Test public void testType() {


        assertEquals(c.suffixSufficient(),true);
    }


    @Test public void testRecognizesFormat() throws IOException {

        // Checker ch = new Checker();

        //create stream here
        final URL tiny = getClass().getResource("tiny-10x10x3.sqy");

        //add an assert here to check contents of tiny

        final RandomAccessInputStream tfile = new RandomAccessInputStream(context,tiny.getPath());

        assertEquals(c.isFormat(tfile),true);
    }


}
